name: note_hub
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # packages
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  open_file: ^3.5.6
  file_picker: ^8.1.2
  flutter_svg: ^2.0.10+1
  hive:
  hive_flutter:
  http:
  image_picker:
  path_provider:
  uuid: ^4.5.1
  dio:
  toastification: ^2.3.0
  
# custom app icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  # image_path: "assets/icons/app_icon.png"
  # adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  image_path: "assets/icons/app_icon_foreground.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/vectors/
    - assets/documents/
    - assets/animations/

  # fonts:
  #   - family:
  #     fonts:
  #       - asset: path/to/font
