name: note_hub
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # packages
  google_fonts:
  flutter_launcher_icons:
  lottie:
  get:
  animated_text_kit:
  intl:
  open_file:
  file_picker:
  flutter_svg:
  hive:
  hive_flutter:
  http:
  image_picker:
  path_provider:
  uuid:
  dio:
  toastification:
  shimmer:

# custom app icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  # image_path: "assets/icons/app_icon.png"
  # adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  image_path: "assets/icons/app_icon_foreground.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/vectors/
    - assets/documents/
    - assets/animations/

  # fonts:
  #   - family:
  #     fonts:
  #       - asset: path/to/font
